language: node_js
node_js:
  - "7"
addons:
  sauce_connect:
    username: "nateben"
    access_key: "d33d8788-b7fa-4e3e-a173-9fbce5fae8bd"
cache:
  directories:
    # - node_modules
    - bower_components
script:
  - yarn add bower
  - ./node_modules/.bin/bower install
  - ./node_modules/.bin/knex migrate:latest
  - npm test
  - .travis/deploy.sh
after_success:
  - .travis/notify.sh "1"
after_failure:
  - .travis/notify.sh "0"
