language: node_js
node_js:
  - "8"
cache:
  directories:
    # - node_modules
    - bower_components
before_script:
  - npm run-script createdb
  - cp .travis/travis.env .env
script:
  - yarn add bower
  - ./node_modules/.bin/knex migrate:latest
  - npm test
after_success:
  - .travis/deploy.sh
  - .travis/notify.sh "1"
after_failure:
  - .travis/notify.sh "0"
services:
  - mysql
