language: node_js
node_js:
  - "8"
cache:
  directories:
    - bower_components
install:
  - yarn install --dev --pure-lockfile
before_script:
  - yarn run createdb
  - cp .travis/travis.env .env
script:
  - yarn run knex migrate:latest
  - yarn run test
after_success:
  - .travis/deploy.sh
  - .travis/notify.sh "1"
after_failure:
  - .travis/notify.sh "0"
services:
  - mysql
