module.exports = [
    {
        event_id: 'MIDBURN2018',
        camp_name_en: 'Campy McCampface',
        camp_desc_en: 'Campful camp',
        type: 'music,drinks', 
        status: 'open',
        contact_person_email: 'alex@midburn.org',
        __prototype: 'theme_camp'
    },
    {
        event_id: 'MIDBURN2018',
        camp_name_en: 'Admin Camp',
        camp_desc_en: 'Privileged Users Only',
        type: 'music,drinks', 
        status: 'open',
        contact_person_email: 'admin@midburn.org',
        __prototype: 'theme_camp'
    },
    {
        "created_at" : "2017-05-25 09:45:13",
        "updated_at" : "2017-05-25 09:45:13",
        "event_id" : "MIDBURN2017",
        "__prototype" : "theme_camp",
        "camp_name_he" : "Sue-me-po",
        "camp_name_en" : "Sue-me-po ",
        "camp_desc_he" : "בית משפט צבעוני וקירקסי. המנצחים מתפנקים. המפסידים נענשים. פינוקים וחיבוקים חמים, עונשים כבדים ושובבים. כלוב עינויים, מיטת עיסויים, הפלקות ישבנים וצלב אחד גדול - למי שהגזים :) ",
        "camp_desc_en" : "A colorful and circus court of justice. The winners indulged. The losers are punished. Treats and warm hugs, heavy and playful punishments. Torture cage, massage bed, Spank asses and one big cross - for those who exaggerate :)",
        "type" : "",
        "status" : "open",
        "web_published" : 1,
        "camp_activity_time" : "",
        "child_friendly" : 0,
        "noise_level" : "quiet",
        "public_activity_area_sqm" : 0,
        "public_activity_area_desc" : "",
        "support_art" : 0,
        "location_comments" : "",
        "camp_location_street" : "null",
        "camp_location_street_time" : "null",
        "camp_location_area" : "",
        "addinfo_json" : null,
        "main_contact" : 1,
        "moop_contact" : null,
        "safety_contact" : null,
        "accept_families" : 0,
        "facebook_page_url" : "",
        "contact_person_email": 'user1@midburn.org',
        "contact_person_id" : 1,
        "pre_sale_tickets_quota" : null
    },
    {
        "created_at" : "2017-05-23 14:39:23",
        "updated_at" : "2017-05-23 14:39:23",
        "event_id" : "MIDBURN2017",
        "__prototype" : "theme_camp",
        "camp_name_he" : "XOXO",
        "camp_name_en" : "XOXO",
        "camp_desc_he" : "יחידת המתנקשים המתנשקים האגדית מגיעה לישראל בפעם הראשונה!! יחידת החיסול המפורסמת בעולם, והיחידה היחידה שמאמינה בחיסול על ידי אהבת חינם, הולכת להפתיע אתכם על הפלאייה ברגעים הכי פחות צפויים.",
        "camp_desc_en" : "The legendary 'Kissing assassins unit' are coming to Israel for the first time ever!! The world-famous assassination unit, and the only one who believes in elimination only by unconditional love, are going to surprise you in the middle of the 'Playa' on the most unexpected moments.",
        "type" : "music,drinks",
        "status" : "closed",
        "web_published" : 1,
        "camp_activity_time" : "evening",
        "child_friendly" : 0,
        "noise_level" : "quiet",
        "public_activity_area_sqm" : null,
        "public_activity_area_desc" : null,
        "support_art" : 0,
        "location_comments" : null,
        "camp_location_street" : null,
        "camp_location_street_time" : null,
        "camp_location_area" : null,
        "addinfo_json" : null,
        "main_contact" : null,
        "moop_contact" : null,
        "safety_contact" : null,
        "accept_families" : 0,
        "facebook_page_url" : "",
        "contact_person_email": 'user2@midburn.org',
        "contact_person_id" : 2,
        "pre_sale_tickets_quota" : null
    },
    {
        "created_at" : "2017-05-23 14:39:23",
        "updated_at" : "2017-05-17 16:52:10",
        "event_id" : "MIDBURN2017",
        "__prototype" : "theme_camp",
        "camp_name_he" : "HOW HOUSE",
        "camp_name_en" : "HOW HOUSE",
        "camp_desc_he" : ", HOW HOUSE הוא הבית של כולנו, בו הכל קורה אבל אף אחד לא ידבר על זה.\nאחרי שתחלצו נעליים בכניסה ותרוצו עירומים בדשא, תרגישו הכי בבית בעולם.\nבבית אפשר להתפרק, לנוח, לעשות כלים, לשאוב אבק ולהתמסר לתחושת הנינוחות היאפית. \nאבל מאחורי האידיליה המשפחתית, האווירה המזמינה והדשא הירוק מידיי, רוחשים כוחות אפלים של כיבוש יצרים ותאוות בשרים. \nואז, כשאתם נינוחים, בדיוק כשתשכחו מכל צרות הפלאיה, נשמוט מתחת ישבנכם את השטיח הפרסי המפואר \nונשלח אתכם להתגלגל מבולבלים ומאובקים באזור הדמדומים של חוסר הגשמה עצמית ואבדן עכבות.\n",
        "camp_desc_en" : "How House - The camp the is home, inside out.\nIt’s our home, the place that no one will tell its secrets. Once you leave your shoes at the entrance, you will instantly feel contained. You will choose to rest, to bark,  to dance, to dust or to sex (...well, and you can always start a conversation about the 10 principles…).\nWhile indulging yourself you must also beware - don’t let the soft couch or the green grass mislead you; behind the walls and inside the rooms there are dark forces of lust and seduction.\n\nAnd just as you settle down, we pull the Persian carpet from right under your feet, sending you downhill, lost and rolling in playa dust, in self fulfillment and moral breakdown.\nWe are going to make you wonder how you can possibly escape or what can you do to stay here forever.\n",
        "type" : "music,art,other=",
        "status" : "closed",
        "web_published" : 1,
        "camp_activity_time" : "night",
        "child_friendly" : 0,
        "noise_level" : "medium",
        "public_activity_area_sqm" : null,
        "public_activity_area_desc" : null,
        "support_art" : 0,
        "location_comments" : null,
        "camp_location_street" : null,
        "camp_location_street_time" : null,
        "camp_location_area" : null,
        "addinfo_json" : null,
        "main_contact" : null,
        "moop_contact" : null,
        "safety_contact" : null,
        "accept_families" : 0,
        "facebook_page_url" : "",
        "contact_person_email": 'user3@midburn.org',
        "contact_person_id" : 3,
        "pre_sale_tickets_quota" : null
    },
    {
        "created_at" : "2017-05-19 02:15:11",
        "updated_at" : "2017-05-19 02:15:11",
        "event_id" : "MIDBURN2017",
        "__prototype" : "art_installation",
        "camp_name_he" : "Lub-dub",
        "camp_name_en" : "DREAM_Lub-dub",
        "camp_desc_he" : null,
        "camp_desc_en" : null,
        "type" : null,
        "status" : "closed",
        "web_published" : 0,
        "camp_activity_time" : null,
        "child_friendly" : null,
        "noise_level" : null,
        "public_activity_area_sqm" : null,
        "public_activity_area_desc" : null,
        "support_art" : null,
        "location_comments" : null,
        "camp_location_street" : null,
        "camp_location_street_time" : null,
        "camp_location_area" : null,
        "addinfo_json" : null,
        "main_contact" : null,
        "moop_contact" : null,
        "safety_contact" : null,
        "accept_families" : null,
        "facebook_page_url" : null,
        "contact_person_email": 'user4@midburn.org',
        "contact_person_id" : 4,
        "pre_sale_tickets_quota" : null
    },
    {
        "created_at" : "2017-05-19 02:15:11",
        "updated_at" : "2017-05-19 02:15:11",
        "event_id" : "MIDBURN2017",
        "__prototype" : "art_installation",
        "camp_name_he" : "איקס 0",
        "camp_name_en" : "DREAM_איקס 0",
        "camp_desc_he" : null,
        "camp_desc_en" : null,
        "type" : null,
        "status" : "closed",
        "web_published" : 0,
        "camp_activity_time" : null,
        "child_friendly" : null,
        "noise_level" : null,
        "public_activity_area_sqm" : null,
        "public_activity_area_desc" : null,
        "support_art" : null,
        "location_comments" : null,
        "camp_location_street" : null,
        "camp_location_street_time" : null,
        "camp_location_area" : null,
        "addinfo_json" : null,
        "main_contact" : null,
        "moop_contact" : null,
        "safety_contact" : null,
        "accept_families" : null,
        "facebook_page_url" : null,
        "contact_person_email": 'user5@midburn.org',
        "contact_person_id" : 5,
        "pre_sale_tickets_quota" : null
    },
    {
        "created_at" : "2017-05-19 02:15:11",
        "updated_at" : "2017-05-26 20:19:10",
        "event_id" : "MIDBURN2017",
        "__prototype" : "art_installation",
        "camp_name_he" : "ספסלי הפלנטות",
        "camp_name_en" : "DREAM_ספסלי הפלנטות",
        "camp_desc_he" : "",
        "camp_desc_en" : "",
        "type" : "",
        "status" : "closed",
        "web_published" : 0,
        "camp_activity_time" : "",
        "child_friendly" : 0,
        "noise_level" : "quiet",
        "public_activity_area_sqm" : 0,
        "public_activity_area_desc" : "",
        "support_art" : 0,
        "location_comments" : "",
        "camp_location_street" : "",
        "camp_location_street_time" : "",
        "camp_location_area" : "",
        "addinfo_json" : null,
        "main_contact" : null,
        "moop_contact" : null,
        "safety_contact" : null,
        "accept_families" : 0,
        "facebook_page_url" : "",
        "contact_person_email": 'user6@midburn.org',
        "contact_person_id" : 6,
        "pre_sale_tickets_quota" : null
    },
    {
        "created_at" : "2017-05-19 02:13:18",
        "updated_at" : "2017-05-26 12:22:06",
        "event_id" : "MIDBURN2017",
        "__prototype" : "prod_dep",
        "camp_name_he" : "Tech",
        "camp_name_en" : "Tech",
        "camp_desc_he" : "",
        "camp_desc_en" : "",
        "type" : "",
        "status" : "closed",
        "web_published" : 0,
        "camp_activity_time" : "",
        "child_friendly" : 0,
        "noise_level" : "quiet",
        "public_activity_area_sqm" : 0,
        "public_activity_area_desc" : "",
        "support_art" : 0,
        "location_comments" : "",
        "camp_location_street" : "",
        "camp_location_street_time" : "",
        "camp_location_area" : "",
        "addinfo_json" : "{\"early_arrival_quota\":\"15\"}",
        "main_contact" : null,
        "moop_contact" : null,
        "safety_contact" : null,
        "accept_families" : 0,
        "facebook_page_url" : "",
        "contact_person_email": 'user7@midburn.org',
        "contact_person_id" : 7,
        "pre_sale_tickets_quota" : 4
    },
    {
        "created_at" : "2017-05-19 02:13:18",
        "updated_at" : "2017-05-27 15:37:35",
        "event_id" : "MIDBURN2017",
        "__prototype" : "prod_dep",
        "camp_name_he" : "אמנות",
        "camp_name_en" : "Art_dep",
        "camp_desc_he" : "",
        "camp_desc_en" : "",
        "type" : "",
        "status" : "closed",
        "web_published" : 0,
        "camp_activity_time" : "",
        "child_friendly" : 0,
        "noise_level" : "quiet",
        "public_activity_area_sqm" : 0,
        "public_activity_area_desc" : "",
        "support_art" : 0,
        "location_comments" : "",
        "camp_location_street" : "",
        "camp_location_street_time" : "",
        "camp_location_area" : "",
        "addinfo_json" : null,
        "main_contact" : null,
        "moop_contact" : null,
        "safety_contact" : null,
        "accept_families" : 0,
        "facebook_page_url" : "",
        "contact_person_email": 'user8@midburn.org',
        "contact_person_id" : 8,
        "pre_sale_tickets_quota" : null
    },
    {
        "created_at" : "2017-05-19 02:13:19",
        "updated_at" : "2017-05-22 19:23:00",
        "event_id" : "MIDBURN2017",
        "__prototype" : "prod_dep",
        "camp_name_he" : "אש",
        "camp_name_en" : "Fire",
        "camp_desc_he" : "",
        "camp_desc_en" : "",
        "type" : "",
        "status" : "closed",
        "web_published" : 0,
        "camp_activity_time" : "",
        "child_friendly" : 0,
        "noise_level" : "quiet",
        "public_activity_area_sqm" : 0,
        "public_activity_area_desc" : "",
        "support_art" : 0,
        "location_comments" : "",
        "camp_location_street" : "",
        "camp_location_street_time" : "",
        "camp_location_area" : "",
        "addinfo_json" : null,
        "moop_contact" : null,
        "safety_contact" : null,
        "accept_families" : 0,
        "facebook_page_url" : "",
        "contact_person_email": 'user9@midburn.org',
        "contact_person_id" : 9,
        "pre_sale_tickets_quota" : null
    }
  ];