module.exports = [
    {
        email: 'admin@midburn.org',
        first_name: 'John', 
        last_name: 'Doe', 
        gender: 'female', 
        validated: true, 
        enabled: true, 
        roles: 'admin',
        password: 'admin'
    },
    {
        email: 'alex@midburn.org',
        first_name: 'alex', 
        last_name: 'alex', 
        gender: 'male', 
        validated: true, 
        enabled: true, 
        roles: 'admin',
        password: 'alex'
    },
    {
        "created_at" : "2015-02-28 20:07:00",
        "updated_at" : "2017-05-17 09:27:54",
        "name" : null,
        "email" : "user1@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "camp_manager",
        "first_name" : "Shaked",
        "last_name" : "Shroit",
        "gender" : "female",
        "date_of_birth" : "1976-01-02",
        "israeli_id" : "038307073",
        "address" : "קיבוץ געש קיבוץ געש IL",
        "cell_phone" : "054-6600799",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 1,
    },
    {
        "created_at" : "2015-01-24 18:19:13",
        "updated_at" : "2017-05-26 15:13:27",
        "name" : null,
        "email" : "user2@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "camp_manager",
        "first_name" : "אורי ",
        "last_name" : "לס",
        "gender" : "female",
        "date_of_birth" : "1991-01-30",
        "israeli_id" : "305435976",
        "address" : "הברוש 2 הרצליה IL",
        "cell_phone" : "0542666360",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 1,
    },
    {
        "created_at" : "2015-01-24 18:19:13",
        "updated_at" : "2017-05-26 15:13:27",
        "name" : null,
        "email" : "user3@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 0,
        "roles" : "camp_manager",
        "first_name" : "אודי",
        "last_name" : "צאיג",
        "gender" : null,
        "date_of_birth" : null,
        "israeli_id" : null,
        "address" : null,
        "cell_phone" : "546594594",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : null,
        "addinfo_json" : null,
    },
    {
        "created_at" : "2015-03-20 14:31:12",
        "updated_at" : "2017-05-27 15:30:03",
        "name" : null,
        "email" : "user4@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "camp_manager",
        "first_name" : "ירון",
        "last_name" : "נחושתן",
        "gender" : "male",
        "date_of_birth" : "1984-08-02",
        "israeli_id" : "066558347",
        "address" : "יהודה המכבי 11 תל אביב IL",
        "cell_phone" : "0547905540",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 1,
    },
    {
        "created_at" : "2015-05-10 18:16:55",
        "updated_at" : "2017-05-20 23:26:23",
        "name" : null,
        "email" : "user5@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "camp_manager",
        "first_name" : "רובים",
        "last_name" : "חוולס",
        "gender" : "male",
        "date_of_birth" : "1976-09-30",
        "israeli_id" : "303531800",
        "address" : "שדרות ירושליים 17, דירה 308 תל אביב- יפו IL",
        "cell_phone" : "0544907196",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 1,
    },
    {
        "created_at" : "2016-01-13 11:09:00",
        "updated_at" : "2017-05-24 18:47:32",
        "name" : null,
        "email" : "user6@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "camp_manager",
        "first_name" : "אדר",
        "last_name" : "נאומן",
        "gender" : "male",
        "date_of_birth" : "1980-03-17",
        "israeli_id" : "032570095",
        "address" : "העבודה 40/5 תל אביב IL",
        "cell_phone" : "0507777728",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 1,
    },
    {
        "created_at" : "2015-09-28 18:39:25",
        "updated_at" : "2017-05-25 09:37:34",
        "name" : null,
        "email" : "user7@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "camp_manager",
        "first_name" : "",
        "last_name" : "",
        "gender" : "female",
        "date_of_birth" : "1991-03-22",
        "israeli_id" : "305492480",
        "address" : "מגדל המנורה 8 מודיעין IL",
        "cell_phone" : "0539281456",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 2,
    },
    {
        "created_at" : "2015-01-24 17:55:50",
        "updated_at" : "2017-06-05 10:45:00",
        "name" : null,
        "email" : "user8@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "camp_manager",
        "first_name" : "איל",
        "last_name" : "חגשורי",
        "gender" : "male",
        "date_of_birth" : "1984-10-15",
        "israeli_id" : "066630252",
        "address" : "ק\"ם 66 תלאביב תל אביב IL",
        "cell_phone" : "0545491638",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 1,
    },
    {
        "created_at" : "2015-01-26 08:34:31",
        "updated_at" : "2017-06-04 17:32:53",
        "name" : null,
        "email" : "user9@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "camp_manager",
        "first_name" : "ארז",
        "last_name" : "בן-קיקי",
        "gender" : "male",
        "date_of_birth" : "1979-11-26",
        "israeli_id" : "021349071",
        "address" : "שד' יהודית 19 תל אביב IL",
        "cell_phone" : "0547460510",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 1,
    },
    {
        "created_at" : "2015-09-30 13:52:26",
        "updated_at" : "2017-05-26 15:44:53",
        "name" : null,
        "email" : "user10@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "camp_manager",
        "first_name" : "עידו",
        "last_name" : "מוסקוביץ",
        "gender" : "male",
        "date_of_birth" : "1983-05-20",
        "israeli_id" : "039232988",
        "address" : "ליפסקי 8 תל אביב IL",
        "cell_phone" : "0506715865",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 1,
    },
    {
        "created_at" : null,
        "updated_at" : null,
        "name" : null,
        "email" : "user11@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 0,
        "roles" : "",
        "first_name" : null,
        "last_name" : null,
        "gender" : null,
        "date_of_birth" : null,
        "israeli_id" : null,
        "address" : null,
        "cell_phone" : null,
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : null,
    },
    {
        "created_at" : "2015-01-24 18:19:13",
        "updated_at" : "2017-05-26 15:13:27",
        "name" : null,
        "email" : "user12@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 0,
        "roles" : "",
        "first_name" : null,
        "last_name" : null,
        "gender" : null,
        "date_of_birth" : null,
        "israeli_id" : null,
        "address" : null,
        "cell_phone" : null,
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : null,
    },
    {
        "created_at" : "2015-03-14 15:52:45",
        "updated_at" : "2017-09-12 13:44:00",
        "name" : null,
        "email" : "user13@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "",
        "first_name" : "נתנאל",
        "last_name" : "בן יורם",
        "gender" : "male",
        "date_of_birth" : "1988-06-16",
        "israeli_id" : "200279594",
        "address" : "המסילה 32 הרצליה IL",
        "cell_phone" : "0542002744",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 1,
    },
    {
        "created_at" : "2016-02-25 23:01:43",
        "updated_at" : "2017-05-21 12:36:04",
        "name" : null,
        "email" : "user14@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "",
        "first_name" : "כפיר",
        "last_name" : "כחלון",
        "gender" : "male",
        "date_of_birth" : "1975-12-14",
        "israeli_id" : "038386306",
        "address" : "בורוכוב 17 חדרה IL",
        "cell_phone" : "050667125",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 2,
    },
    {
        "created_at" : "2015-01-24 18:19:13",
        "updated_at" : "2017-05-26 15:13:27",
        "name" : null,
        "email" : "user15@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 0,
        "roles" : "",
        "first_name" : "Yossi",
        "last_name" : "Landesrocha",
        "gender" : null,
        "date_of_birth" : null,
        "israeli_id" : "033197542",
        "address" : null,
        "cell_phone" : null,
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : null,
    },
    {
        "created_at" : "2015-09-23 10:24:39",
        "updated_at" : "2017-05-21 13:38:32",
        "name" : null,
        "email" : "user16@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "",
        "first_name" : "נטלי",
        "last_name" : "כץ-אסולין",
        "gender" : "female",
        "date_of_birth" : "1972-05-15",
        "israeli_id" : "029253903",
        "address" : "יוסף פישר 30 קרית ביאליק IL",
        "cell_phone" : "0528775113",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 1,
    },
    {
        "created_at" : "2016-01-07 00:06:12",
        "updated_at" : "2017-04-24 14:01:56",
        "name" : null,
        "email" : "user17@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "",
        "first_name" : "Sharon",
        "last_name" : "Greenberg ",
        "gender" : "male",
        "date_of_birth" : "1975-12-16",
        "israeli_id" : "038305223",
        "address" : "האלונים 18 נתניה IL",
        "cell_phone" : "0502010011",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 1,
    },
    {
        "created_at" : "2015-01-24 18:19:13",
        "updated_at" : "2017-05-26 15:13:27",
        "name" : null,
        "email" : "user18@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "",
        "first_name" : "דור",
        "last_name" : "עמית",
        "gender" : "other",
        "date_of_birth" : null,
        "israeli_id" : "039837786",
        "address" : null,
        "cell_phone" : "054-976001",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : null,
    },
    {
        "created_at" : "2017-04-10 04:25:03",
        "updated_at" : "2017-04-28 10:22:58",
        "name" : null,
        "email" : "user19@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "",
        "first_name" : "עודד",
        "last_name" : "מנסטר",
        "gender" : "male",
        "date_of_birth" : "1972-06-07",
        "israeli_id" : "029624871",
        "address" : "בנימין 2 רמת גן רמת גן IL",
        "cell_phone" : "0506557352",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 1,
    },
    {
        "created_at" : "2017-02-12 12:17:34",
        "updated_at" : "2017-05-14 15:53:45",
        "name" : null,
        "email" : "user20@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "",
        "first_name" : "עמוס",
        "last_name" : "שפרינגר",
        "gender" : "male",
        "date_of_birth" : "1972-10-18",
        "israeli_id" : "029698701",
        "address" : "בן גוריון 61 קרית ביאליק קרית ביאליק IL",
        "cell_phone" : "0523868370",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 1,
    }
  ];