module.exports = [
    {
        email: 'admin@midburn.org',
        first_name: 'John', 
        last_name: 'Doe', 
        gender: 'female', 
        validated: true, 
        enabled: true, 
        roles: 'admin',
        password: 'admin'
    },
    {
        email: 'alex@midburn.org',
        first_name: 'alex', 
        last_name: 'alex', 
        gender: 'male', 
        validated: true, 
        enabled: true, 
        roles: 'admin',
        password: 'alex'
    },
    {
        "created_at" : "2015-02-28 20:07:00",
        "updated_at" : "2017-05-17 09:27:54",
        "name" : null,
        "email" : "user1@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "camp_manager",
        "first_name" : "first1",
        "last_name" : "last1",
        "gender" : "female",
        "date_of_birth" : "1976-01-02",
        "israeli_id" : "0000",
        "address" : "קיבוץ געש קיבוץ געש IL",
        "cell_phone" : "0000",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 1,
    },
    {
        "created_at" : "2015-01-24 18:19:13",
        "updated_at" : "2017-05-26 15:13:27",
        "name" : null,
        "email" : "user2@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "camp_manager",
        "first_name" : "פרטי2",
        "last_name" :"משפחה2",
        "gender" : "female",
        "date_of_birth" : "1991-01-30",
        "israeli_id" : "0000",
        "address" : "הברוש 2 הרצליה IL",
        "cell_phone" : "0000",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 1,
    },
    {
        "created_at" : "2015-01-24 18:19:13",
        "updated_at" : "2017-05-26 15:13:27",
        "name" : null,
        "email" : "user3@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 0,
        "roles" : "camp_manager",
        "first_name" : "פרטי3",
        "last_name" : "משפחה3",
        "gender" : null,
        "date_of_birth" : null,
        "israeli_id" : null,
        "address" : null,
        "cell_phone" : "0000",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : null,
        "addinfo_json" : null,
    },
    {
        "created_at" : "2015-03-20 14:31:12",
        "updated_at" : "2017-05-27 15:30:03",
        "name" : null,
        "email" : "user4@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "camp_manager",
        "first_name" : "פרטי4",
        "last_name" : "מפשחה4",
        "gender" : "male",
        "date_of_birth" : "1984-08-02",
        "israeli_id" : "0000",
        "address" : "יהודה המכבי 11 תל אביב IL",
        "cell_phone" : "0000",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 1,
    },
    {
        "created_at" : "2015-05-10 18:16:55",
        "updated_at" : "2017-05-20 23:26:23",
        "name" : null,
        "email" : "user5@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "camp_manager",
        "first_name" : "פרטי5",
        "last_name" : "משפחה5",
        "gender" : "male",
        "date_of_birth" : "1976-09-30",
        "israeli_id" : "0000",
        "address" : "שדרות ירושליים 17, דירה 308 תל אביב- יפו IL",
        "cell_phone" : "0000",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 1,
    },
    {
        "created_at" : "2016-01-13 11:09:00",
        "updated_at" : "2017-05-24 18:47:32",
        "name" : null,
        "email" : "user6@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "camp_manager",
        "first_name" : "פרטי6",
        "last_name" : "משפחה6",
        "gender" : "male",
        "date_of_birth" : "1980-03-17",
        "israeli_id" : "032570095",
        "address" : "העבודה 40/5 תל אביב IL",
        "cell_phone" : "0000",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 1,
    },
    {
        "created_at" : "2015-09-28 18:39:25",
        "updated_at" : "2017-05-25 09:37:34",
        "name" : null,
        "email" : "user7@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "camp_manager",
        "first_name" : "",
        "last_name" : "",
        "gender" : "female",
        "date_of_birth" : "1991-03-22",
        "israeli_id" : "0000",
        "address" : "מגדל המנורה 8 מודיעין IL",
        "cell_phone" : "0000",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 2,
    },
    {
        "created_at" : "2015-01-24 17:55:50",
        "updated_at" : "2017-06-05 10:45:00",
        "name" : null,
        "email" : "user8@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "camp_manager",
        "first_name" : "פרטי7",
        "last_name" : "משפחה7",
        "gender" : "male",
        "date_of_birth" : "1984-10-15",
        "israeli_id" : "0000",
        "address" : "ק\"ם 66 תלאביב תל אביב IL",
        "cell_phone" : "0000",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 1,
    },
    {
        "created_at" : "2015-01-26 08:34:31",
        "updated_at" : "2017-06-04 17:32:53",
        "name" : null,
        "email" : "user9@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "camp_manager",
        "first_name" : "פרטי9",
        "last_name" : "משפחה9",
        "gender" : "male",
        "date_of_birth" : "1979-11-26",
        "israeli_id" : "0000",
        "address" : "שד' יהודית 19 תל אביב IL",
        "cell_phone" : "0000",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 1,
    },
    {
        "created_at" : "2015-09-30 13:52:26",
        "updated_at" : "2017-05-26 15:44:53",
        "name" : null,
        "email" : "user10@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "camp_manager",
        "first_name" : "פרטי10",
        "last_name" : "משפחה10",
        "gender" : "male",
        "date_of_birth" : "1983-05-20",
        "israeli_id" : "0000",
        "address" : "ליפסקי 8 תל אביב IL",
        "cell_phone" : "0000",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 1,
    },
    {
        "created_at" : null,
        "updated_at" : null,
        "name" : null,
        "email" : "user11@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 0,
        "roles" : "",
        "first_name" : null,
        "last_name" : null,
        "gender" : null,
        "date_of_birth" : null,
        "israeli_id" : null,
        "address" : null,
        "cell_phone" : null,
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : null,
    },
    {
        "created_at" : "2015-01-24 18:19:13",
        "updated_at" : "2017-05-26 15:13:27",
        "name" : null,
        "email" : "user12@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 0,
        "roles" : "",
        "first_name" : null,
        "last_name" : null,
        "gender" : null,
        "date_of_birth" : null,
        "israeli_id" : null,
        "address" : null,
        "cell_phone" : null,
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : null,
    },
    {
        "created_at" : "2015-03-14 15:52:45",
        "updated_at" : "2017-09-12 13:44:00",
        "name" : null,
        "email" : "user13@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "",
        "first_name" : "פרטי13",
        "last_name" : "משפחה13",
        "gender" : "male",
        "date_of_birth" : "1988-06-16",
        "israeli_id" : "0000",
        "address" : "המסילה 32 הרצליה IL",
        "cell_phone" : "0000",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 1,
    },
    {
        "created_at" : "2016-02-25 23:01:43",
        "updated_at" : "2017-05-21 12:36:04",
        "name" : null,
        "email" : "user14@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "",
        "first_name" : "פרטי14",
        "last_name" : "משפחה14",
        "gender" : "male",
        "date_of_birth" : "1975-12-14",
        "israeli_id" : "0000",
        "address" : "בורוכוב 17 חדרה IL",
        "cell_phone" : "0000",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 2,
    },
    {
        "created_at" : "2015-01-24 18:19:13",
        "updated_at" : "2017-05-26 15:13:27",
        "name" : null,
        "email" : "user15@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 0,
        "roles" : "",
        "first_name" : "first15",
        "last_name" : "last15",
        "gender" : null,
        "date_of_birth" : null,
        "israeli_id" : "0000",
        "address" : null,
        "cell_phone" : null,
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : null,
    },
    {
        "created_at" : "2015-09-23 10:24:39",
        "updated_at" : "2017-05-21 13:38:32",
        "name" : null,
        "email" : "user16@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "",
        "first_name" : "פרטי16",
        "last_name" : "משפחה16",
        "gender" : "female",
        "date_of_birth" : "1972-05-15",
        "israeli_id" : "0000",
        "address" : "יוסף פישר 30 קרית ביאליק IL",
        "cell_phone" : "0000",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 1,
    },
    {
        "created_at" : "2016-01-07 00:06:12",
        "updated_at" : "2017-04-24 14:01:56",
        "name" : null,
        "email" : "user17@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "",
        "first_name" : "first17",
        "last_name" : "last17",
        "gender" : "male",
        "date_of_birth" : "1975-12-16",
        "israeli_id" : "0000",
        "address" : "האלונים 18 נתניה IL",
        "cell_phone" : "0000",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 1,
    },
    {
        "created_at" : "2015-01-24 18:19:13",
        "updated_at" : "2017-05-26 15:13:27",
        "name" : null,
        "email" : "user18@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "",
        "first_name" : "פרטי18",
        "last_name" : "משפחה18",
        "gender" : "other",
        "date_of_birth" : null,
        "israeli_id" : "0000",
        "address" : null,
        "cell_phone" : "00000",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : null,
    },
    {
        "created_at" : "2017-04-10 04:25:03",
        "updated_at" : "2017-04-28 10:22:58",
        "name" : null,
        "email" : "user19@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "",
        "first_name" : "פרטי19",
        "last_name" : "משפחה19",
        "gender" : "male",
        "date_of_birth" : "1972-06-07",
        "israeli_id" : "0000",
        "address" : "בנימין 2 רמת גן רמת גן IL",
        "cell_phone" : "0000",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 1,
    },
    {
        "created_at" : "2017-02-12 12:17:34",
        "updated_at" : "2017-05-14 15:53:45",
        "name" : null,
        "email" : "user20@midburn.org",
        "password" : null,
        "enabled" : 1,
        "validated" : 1,
        "roles" : "",
        "first_name" : "פרטי20",
        "last_name" : "משפחה20",
        "gender" : "male",
        "date_of_birth" : "1972-10-18",
        "israeli_id" : "0000",
        "address" : "בן גוריון 61 קרית ביאליק קרית ביאליק IL",
        "cell_phone" : "0000",
        "extra_phone" : null,
        "npo_member" : 0,
        "facebook_id" : null,
        "facebook_token" : null,
        "current_event_id" : null,
        "current_status" : null,
        "current_event_id_ticket_count" : 1,
    }
  ];